# .github/workflows/dataset-check.yml
name: dataset-check
on: [pull_request, push]
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.12"}
      - run: pip install pillow "dvc[gdrive]"  # + dep lain
      - run: dvc pull                        # ambil data
      - run: python scripts/sanity_check.py --root data/raw --out docs/data_report.json
