# .github/workflows/dvc-ci.yml

name: DVC CI
on:
  push:
    branches:
      - master

jobs:
  dvc-check:
    runs-on: ubuntu-latest

    env:
      GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}

    steps:
      # 2. Ambil (checkout) source code dari repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 3. Siapkan Python (misal versi 3.12; bisa diganti sesuai kebutuhan)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 4. Instal DVC, Jupyter, dan dependencies Python lainnya
      - name: Install DVC and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            dvc[gdrive] \
            jupyter \
            nbconvert \
            pandas \
            numpy \
            matplotlib \
            scikit-learn \
            pillow \
            opencv-python \
            albumentations \
            pytest

      # 5. Rekonstruksi file Service Account JSON dari secret GitHub ke folder credentials/
      - name: Recreate Service Account JSON
        run: |
          mkdir -p credentials
          cat <<EOF > credentials/service-account.json
          ${{ env.GDRIVE_SERVICE_ACCOUNT_JSON }}
          EOF
          echo "=== First 5 lines of credentials/service-account.json ==="
          head -n 5 credentials/service-account.json

      # 6. Konfigurasikan DVC agar menggunakan Service Account JSON
      - name: Configure DVC Remote for Google Drive
        run: |
          # Ganti FOLDER_ID dan SA_EMAIL sesuai project Google Drive Anda
          FOLDER_ID=1slQ2wu0Lz_DPKCeKE0kZ-mge1qhUAM3e
          SA_EMAIL=dvc-gdrive-sa@seismic-octane-441403-b9.iam.gserviceaccount.com

          # Jika DVC belum di-init di repo, uncomment baris berikut:
          # dvc init

          # Tambahkan remote (force overwrite jika sudah ada)
          dvc remote remove gdrive_remote || true
          dvc remote add -d gdrive_remote "gdrive://${FOLDER_ID}"

          # Aktifkan penggunaan Service Account
          dvc remote modify gdrive_remote gdrive_use_service_account true

          # Set lokal config agar path ke JSON tidak tercatat di Git
          dvc remote modify gdrive_remote --local \
            gdrive_service_account_json_file_path credentials/service-account.json
          dvc remote modify gdrive_remote --local \
            gdrive_service_account_user_email "${SA_EMAIL}"

      # 7. Tarik data dari DVC remote
      - name: DVC Pull
        run: |
          dvc pull -q

      # 8. Stratified split via DVC
      - name: Run stratified split via DVC
        run: |
          dvc repro split_dataset

      # 9. Upload hasil split ke remote
      - name: Push processed split to remote
        run: |
          dvc push -q split_dataset

      # 10. Jalankan unit test untuk dataset split
      - name: Run dataset unit tests
        run: |
          pytest tests/test_dataset.py

      # 11. Augmentation preview & unit tests
      - name: Generate aug samples & run augment tests
        run: |
          dvc repro augment_preview
          pytest tests/test_augment.py

      # 12. Build EDA report
      - name: Build EDA report
        run: |
          dvc repro eda_report

      # 13. Upload EDA HTML sebagai artefak
      - name: Upload EDA HTML
        uses: actions/upload-artifact@v3
        with:
          name: eda-report
          path: docs/eda_dataset.html
